#!/bin/bash

[[ -s /etc/default/evm ]] && source /etc/default/evm

# Init postgresql DB, inject role and start up service

echo " = INIT DB = "

set -e 

if [ ! -d ${APPLIANCE_PG_DATA}/base ]; then
  chown postgres:postgres ${APPLIANCE_PG_DATA}
  su postgres -c "initdb -D ${APPLIANCE_PG_DATA}"
  su postgres -c "pg_ctl -D ${APPLIANCE_PG_DATA} start"
  sleep 5
  su postgres -c "psql -c \"CREATE ROLE root SUPERUSER LOGIN PASSWORD 'smartvm'\""
else
  su postgres -c "pg_ctl -D ${APPLIANCE_PG_DATA} start"
fi

# Start memcached
/usr/bin/memcached -u memcached -d

# Install deps
cd ${APP_ROOT}  

# setup manageiq-ui-classic repo
mkdir plugins
git clone https://github.com/ManageIQ/manageiq-ui-classic plugins/manageiq-ui-classic

# setup Gemfile.dev.rb
echo "= writing to Gemfile.dev.rb ="
echo "override_gem 'manageiq-ui-classic', :path => File.expand_path('plugins/manageiq-ui-classic', __dir__)" > Gemfile.dev.rb

# setup managiq sample app
ln -s ${APP_ROOT} plugins/manageiq-ui-classic/spec/manageiq

base_address="https://github.com/ManageIQ/"

for ARG in "$@"
do
  git clone $base_address/$ARG plugins/$ARG
  echo "= writing 'override_gem '$ARG', :path => File.expand_path('plugins/manageiq-ui-classic', __dir__)' to Gemfile.dev.rb ="
  echo "override_gem '$ARG', :path => File.expand_path('plugins/$ARG', __dir__)" >> Gemfile.dev.rb
  ln -s ${APP_ROOT} plugins/$ARG/spec/manageiq
done

# prepare DB
bin/setup --no-tests

[[ -s /etc/default/evm ]] && source /etc/default/evm

set -e

# init app
cd ${APP_ROOT}
rake evm:start
exec bin/rails server

